'use client'

import { useState, useEffect } from 'react'
import AdminSidebar from '@/components/AdminSidebar'
import BottomBar from '@/components/BottomBar'
import { Plus, Layout, Edit3, Eye, Trash2, ChevronLeft, Search, FileText, Download } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import TemplateEditor from '@/components/undangan/TemplateEditor'
import { toast } from 'react-hot-toast'
import { getTemplates, saveTemplate, deleteTemplate, Template } from '@/app/actions/templates'
import { saveAs } from 'file-saver'

export default function TemplatesPage() {
  const router = useRouter()
  const [templates, setTemplates] = useState<Template[]>([])
  const [loading, setLoading] = useState(true)
  const [isEditorOpen, setIsEditorOpen] = useState(false)
  const [editingTemplate, setEditingTemplate] = useState<Template | null>(null)
  const [search, setSearch] = useState('')

  useEffect(() => {
    const checkUser = async () => {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) {
        router.push('/undangan/login')
      } else {
        fetchData()
      }
    }
    
    checkUser()
  }, [])

  const fetchData = async () => {
    setLoading(true)
    const data = await getTemplates()
    setTemplates(data)
    setLoading(false)
  }

  const handleAdd = () => {
    setEditingTemplate({
      id: '', // Will be generated by Supabase
      name: '',
      content: '<h1>Judul Undangan</h1><p>Isi undangan di sini...</p>',
      category: 'Umum'
    })
    setIsEditorOpen(true)
  }

  const handleDownloadTemplate = async (template: Template) => {
    if (!template.content.startsWith('http')) {
      toast.error('Template ini tidak memiliki file fisik.')
      return
    }
    
    try {
      const response = await fetch(template.content)
      const blob = await response.blob()
      saveAs(blob, `${template.name}.docx`)
      toast.success('Template berhasil diunduh.')
    } catch (err) {
      console.error(err)
      toast.error('Gagal mengunduh template.')
    }
  }

  const handleEdit = (template: Template) => {
    setEditingTemplate(template)
    setIsEditorOpen(true)
  }

  const handleSave = async (template: Template) => {
    const { error } = await saveTemplate(template)
    if (error) {
      toast.error('Gagal menyimpan: ' + error.message)
    } else {
      toast.success(template.id ? 'Template diperbarui!' : 'Template baru ditambahkan!')
      fetchData()
      setIsEditorOpen(false)
    }
  }

  const handleDelete = async (id: string) => {
    if (confirm('Hapus template ini?')) {
      const { error } = await deleteTemplate(id)
      if (error) {
        toast.error('Gagal menghapus')
      } else {
        toast.success('Template dihapus')
        fetchData()
      }
    }
  }

  return (
    <main className="min-h-dvh flex bg-zinc-50/30 overflow-hidden relative font-sans">
      <AdminSidebar mode="undangan" />

      <div className="flex-1 flex flex-col h-dvh overflow-hidden">
        <header className="p-6 lg:p-10 pb-0 shrink-0">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <button 
                onClick={() => router.push('/undangan')}
                className="p-3 bg-white border-2 border-zinc-100 rounded-2xl hover:bg-zinc-50 transition-colors"
              >
                <ChevronLeft size={20} />
              </button>
              <div>
                <h1 className="text-3xl font-black uppercase tracking-tighter text-zinc-900">Manajemen Template</h1>
                <p className="text-xs font-bold text-zinc-400 uppercase tracking-widest">Atur format surat undangan</p>
              </div>
            </div>

            <button 
              onClick={handleAdd}
              className="cartoon-btn bg-[#ffdc00] px-8 h-14 flex items-center gap-2 font-black uppercase text-[10px] tracking-widest shadow-lg"
            >
              <Plus size={20} strokeWidth={3} /> Tambah Template
            </button>
          </div>

          <div className="relative mb-8 max-w-xl">
             <Search className="absolute left-6 top-1/2 -translate-y-1/2 text-black/20" size={20} />
             <input 
               type="text"
               placeholder="Cari template..."
               className="cartoon-input w-full pl-16! h-14 bg-white shadow-sm border-zinc-100"
               value={search}
               onChange={(e) => setSearch(e.target.value)}
             />
          </div>
        </header>

        <div className="flex-1 overflow-y-auto px-6 lg:p-10 pt-0 no-scrollbar pb-24">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {templates.filter(t => t.name.toLowerCase().includes(search.toLowerCase())).map(template => (
              <motion.div 
                key={template.id}
                layoutId={template.id}
                className="cartoon-card bg-white p-6 group hover:border-primary transition-all"
              >
                <div className="flex justify-between items-start mb-6">
                  <div className={`w-12 h-12 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform ${template.content.startsWith('file:') ? 'bg-blue-50 text-blue-500' : 'bg-orange-50 text-orange-500'}`}>
                    {template.content.startsWith('file:') ? <FileText size={24} /> : <Layout size={24} />}
                  </div>
                  <div className={`px-3 py-1 rounded-full text-[8px] font-black uppercase tracking-widest ${template.content.startsWith('file:') ? 'bg-blue-100 text-blue-600' : 'bg-orange-100 text-orange-600'}`}>
                    {template.content.startsWith('file:') ? 'DOCX' : 'HTML'}
                  </div>
                </div>
                
                <h3 className="text-xl font-black text-zinc-900 mb-2 truncate group-hover:text-primary transition-colors">{template.name}</h3>
                <span className="text-[9px] font-bold uppercase text-zinc-400 tracking-widest">{template.category}</span>
                
                <div className="grid grid-cols-2 gap-2 mt-8">
                  <button 
                    onClick={() => handleEdit(template)}
                    className="h-10 bg-zinc-50 rounded-xl flex items-center justify-center gap-2 font-bold text-[10px] uppercase tracking-widest hover:bg-zinc-900 hover:text-white transition-all"
                  >
                    <Edit3 size={14} /> Edit
                  </button>
                  <button 
                    onClick={() => handleDownloadTemplate(template)}
                    className="h-10 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center gap-2 font-bold text-[10px] uppercase tracking-widest hover:bg-blue-600 hover:text-white transition-all"
                  >
                    <Download size={14} /> Docx
                  </button>
                  <button 
                    onClick={() => handleDelete(template.id)}
                    className="h-10 border-2 border-zinc-50 rounded-xl flex items-center justify-center gap-2 font-bold text-[10px] uppercase tracking-widest hover:border-secondary hover:text-secondary transition-all col-span-2"
                  >
                    <Trash2 size={14} /> Hapus
                  </button>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      <AnimatePresence>
        {isEditorOpen && editingTemplate && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-100 bg-black/60 flex items-center justify-center p-6"
          >
            <motion.div 
              initial={{ scale: 0.95, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.95, y: 20 }}
              className="bg-white w-full max-w-6xl max-h-[95vh] rounded-[2rem] lg:rounded-[3.5rem] p-6 lg:p-10 shadow-2xl relative overflow-y-auto"
            >
              <div className="flex justify-between items-center mb-6 lg:mb-8 shrink-0">
                <div>
                  <h2 className="text-xl lg:text-3xl font-black uppercase tracking-tighter">Editor Template</h2>
                  <p className="text-[10px] lg:text-xs font-bold text-zinc-400 uppercase tracking-widest mt-1">Sesuaikan desain undanganmu</p>
                </div>
                <button 
                  onClick={() => setIsEditorOpen(false)}
                  className="p-4 bg-zinc-50 text-zinc-400 rounded-3xl hover:bg-zinc-100 hover:text-zinc-900 transition-all"
                >
                  <X size={24} strokeWidth={3} />
                </button>
              </div>
              
              <div className="flex-1 overflow-hidden">
                <TemplateEditor 
                  template={editingTemplate} 
                  onSave={handleSave} 
                  onClose={() => setIsEditorOpen(false)} 
                />
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
      <BottomBar />
    </main>
  )
}

function X({ size, strokeWidth, ...props }: any) {
  return (
    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      width={size} 
      height={size} 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth={strokeWidth} 
      strokeLinecap="round" 
      strokeLinejoin="round" 
      {...props}
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
